- Code/pom.xml
- Code/src/main/java/nl/utwente/group10/App.java
This PR cleans up some unneeded stuff (and Cobertura) from the pom.xml file to
make it a bit easier to read. It also replaces the jar generation plugin with
one that bundles dependencies, which makes it easier to distribute the end
result.
> Small improvements to pom.xml

- .travis.yml
This adds a virtual framebuffer to Travis, which means that tests that
use JavaFX should no longer complain about not being to open a display.
> Add xvfb virtual framebuffer to .travis.yml

- Code/pom.xml
Maven builds will now fail when the catalog XML file is invalid.
> Check XML files during maven build

- Code/src/main/java/nl/utwente/group10/ui/components/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java
Refactored FunctionBlock in order to make feature expansion easier.
FunctionBlock now extends Block and certain methods have subsequently been moved from FunctionBlock to Block.
newInstance of FunctionBlock has been slightly rewritten and a second version of newInstance has been introduced to enable the instantiation of FunctionBlocks with initialised names.
> Refactoring of FunctionBlock

- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/Main.java
- Code/src/main/java/nl/utwente/group10/ui/components/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/gestures/CustomGesture.java
- Code/src/main/java/nl/utwente/group10/ui/gestures/GestureCallBack.java
- Code/src/main/java/nl/utwente/group10/ui/gestures/UIEvent.java
CustomGestureEvent wordt niet meer gebruikt. In plaats hiervan is dit nu UIEvent. De code is echter hetzelfde gebleven. Verder vangt (Function)Block nu ook events af en houdt een (Function)Block bij in welke CustomUIPane deze zit i.v.m. het selecteren van ander (Function)Blocks.
Een (Function)Block kan nu geselecteerd worden door er op te klikken. Bij het klikken op een ander (Function)Block vervalt een eventuele andere selectie
> function block select & drag gesture

- Code/src/test/java/nl/utwente/group10/ui/components/ComponentTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/ValueBlockTest.java
The JavaFX Init thread was not created for the ValueBlockTest, which
meant it only passed if it happened to be run after the
DisplayBlockTest. This commit resolves that problem.
It also ensures no more than one such thread is ever created.
> Fix JavaFX init thread for ValueBlockTest

- Code/src/main/resources/catalog/functions.xml
This adds some Float-specialized variants of Haskell's prelude math functions
to the catalog. (The signatures are specialized because type classes aren't
supported yet.)
> Add more math functions to the catalog

- Code/src/main/java/nl/utwente/group10/ghcj/GhciSession.java
- Code/src/main/java/nl/utwente/group10/haskell/catalog/Entry.java
- Code/src/main/java/nl/utwente/group10/haskell/catalog/HaskellCatalog.java
- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/Main.java
- Code/src/main/java/nl/utwente/group10/ui/components/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/Connection.java
- Code/src/main/java/nl/utwente/group10/ui/components/ConnectionAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/InputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/OutputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/ValueBlock.java
- Code/src/main/resources/ui/FunctionBlock.fxml
- Code/src/test/java/nl/utwente/group10/ghcj/GhciEvaluatorTest.java
- Code/src/test/java/nl/utwente/group10/ghcj/GhciSessionTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/DisplayBlockTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/ValueBlockTest.java
This PR adds enough functionality to do basic calculator-like computation. It includes the InputAnchor/OutputAnchor split, a rudimentary integration with the backend that doesn't do type checking, and a way to add (but not delete) functions and lines.
> Add basic calculator functionality

- Report/.gitignore
- Report/Chapters/Bibliography.bib
- Report/Chapters/Bibliography.tex
- Report/Chapters/Glossary.tex
- Report/Chapters/Implementation.tex
- Report/Chapters/Preface.tex
- Report/report.tex
This PR adds a short blurb about the type checker to the report.
It also changes the bibliography system to use the more convenient BibTeX and adds some useful sources.
> Add a short blurb about type checker to report

- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/components/Block.java
- Code/src/main/resources/ui/style.css
- Code/src/test/java/nl/utwente/group10/ui/components/DisplayBlockTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/ValueBlockTest.java
This commit reworks the selection state of function blocks so that only
one block can be selected at any time. It also contains a style so that
selected function blocks show sky blue instead of alice blue.
> Show selected state of function blocks

- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/MainMenu.java
- Code/src/main/java/nl/utwente/group10/ui/components/Connection.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java
- Code/src/main/resources/ui/style.css
* Connections now turn red when there is a type mismatch between both ends.
* Argument fields in FunctionBlock now have red outlining whenever their InputAnchors have no input.
* **Highlighted issue**: there seems to be no discernible way to access the Env or GenSet values for the application, this makes evaluation requests by components seemingly impossible. See TODO in Connection.java
> UI Visual feedback for missing arguments and type mismatches

- Code/src/main/antlr4/nl/utwente/group10/haskell/typeparser/Type.g4
- Code/src/main/java/nl/utwente/group10/haskell/typeparser/TypeBuilderListener.java
- Code/src/test/java/nl/utwente/group10/haskell/typeparser/TypeBuilderTest.java
Fixes the issues where...
- ... a typeclass contains an uppercase character after the first position (e.g. ```RealFrac```). This was an issue with the lexer.
- ... an unknown typeclass is ignored by the parser where it unintentionally falled back to the last used type class.
> Fixes for type classes

- Code/src/main/java/nl/utwente/group10/haskell/catalog/Catalog.java
When running from a JAR file, resources can't be opened directly:
they're not files on their own and therefore do not really have a path.
They can, however, be opened; the InputStream can then be passed to
`parse`.
This should fix the JAR file generated by `mvn package`.
> Parse Catalog from stream instead of from path

- Code/src/main/java/nl/utwente/group10/ui/handlers/ConnectionCreationManager.java
This always draws new connections behind blocks, instead of drawing them in
front at first, then sinking to the back as blocks get selected and brought to
the front by TactilePane.
> Fix draw order of connections

- Code/src/main/java/nl/utwente/ewi/caes/tactilefx/control/PhysicsTimer.java
- Code/src/main/java/nl/utwente/ewi/caes/tactilefx/control/TactilePane.java
- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/Main.java
- Code/src/main/java/nl/utwente/group10/ui/MainMenu.java
- Code/src/main/java/nl/utwente/group10/ui/components/anchors/ConnectionAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/lines/Connection.java
- Code/src/main/java/nl/utwente/group10/ui/handlers/ConnectionCreationManager.java
- Code/src/main/resources/ui/Main.fxml
- Code/src/main/resources/ui/style.css
This commit adds panning and zooming functionality.
Pan is implemented by translating the TactilePane in the correct (that
is, opposite) direction. Similarly, zooming is implemented by scaling
the TactilePane.
The code for TactilePane is changed to use pane-relative instead of
scene-relative coordinates at some points, as scene-relative coordinates
do not take into account the transformations applied.
Touch interaction is untested.
> Implement panning (drag) and zooming (scroll)

- Code/src/main/java/nl/utwente/group10/ghcj/GhciSession.java
- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/test/java/nl/utwente/group10/ghcj/GhciSessionTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/blocks/DisplayBlockTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/blocks/FunctionBlockTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/blocks/ValueBlockTest.java
There were reasons for making GhciSession a singleton, but none of them
were very good. This commit reverts that and has CustomUIPane carry
along an optional GhciSession.
> Make GhciSession NOT a Singleton

- Code/src/main/java/nl/utwente/group10/ui/components/ComponentLoader.java
- Code/src/main/java/nl/utwente/group10/ui/components/CustomAlert.java
- Code/src/main/java/nl/utwente/group10/ui/components/anchors/ConnectionAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/anchors/InputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/anchors/OutputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/lines/ConnectionLine.java
- Code/src/main/java/nl/utwente/group10/ui/menu/MainMenu.java
This changes the ComponentLoader interface to itself catch IOExceptions
and rethrow them as RuntimeExceptions.
Not throwing IOExceptions simplifies quite a few methods, as well as the
MainMenu class.
Rationale: When an FXML file can not be read, that's *always* a fatal
error. In other words, the program is useless when it does not have all
its FXML files. In the old implementation, none of the places that
caught the exception did something useful with it.
> Have ComponentLoader swallow/rethrow IOExceptions

- Code/src/main/java/nl/utwente/group10/haskell/type/TypeClass.java
Set.contains returns true if its argument is equal to any of the set's
elements, but we do not override equals() or hashCode() on Type. We do
implement Comparable, however, so that is what we use here.
Complexity gone from possible O(1) to definite O(N), but N is small.
> Fix contains check in TypeClass (with compareTo)

- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/InputBlock.java
The current implementation has getOutputType skip analyzing if one or more inputs of the function block are not connected. However, we might not need the disconnected input to say something sensible about the output type. So instead of this:
The PR tells FunctionBlock to always analyze:
As an added bonus, not having to be able to check if inputs are connected simplifies the InputBlock interface a bit.
> Have FunctionBlock.getOutputType always analyze()

- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/InputBlock.java
- Code/src/test/java/nl/utwente/group10/haskell/type/ApplyTest.java
- Code/src/test/java/nl/utwente/group10/ui/components/blocks/FunctionBlockTest.java
Hierbij een PR dat FunctionBlocks ondersteuning geeft voor een bowtie.
Er is nog geen ui besturing om deze bowtie te veranderen (of uberhaupt weer te geven), maar FunctionBlock heeft nu een property die de index van de bowtie specifieerd, en alle types e.d. houden hier nu rekening mee.
Daarbij heb ik een nieuwe bug gevonden in de backend, het opvragen van het type van "(+) undefined" geeft een error, wat volgens gchi een 'Num a => a -> a' moet zijn.
Ik weet niet of het handig is die test hier bij in te doen, graag zou ik willen weten wat hier de handigste werkwijze voor is.
> Ui types bowtie

- Code/src/test/java/nl/utwente/group10/haskell/type/BubbleTest.java
- Code/src/test/java/nl/utwente/group10/haskell/type/SharingTest.java
This PR adds a few 'demonstration' tests/smoke tests for the backend.
- `BubbleTest.testBubbleUnit` shows how information about the type of a function seems to 'bubble' to the inferred types of its arguments.
- `BubbleTest.testBubbleAddition` succesfully runs type inference for the program in #85. 
- `BubbleTest.testBubbleEquals` succesfully runs type inference for the program in #87.
- `SharingTest.testSharedSimple` demonstrates that VarT's are shared and that `unify` can affect more than just its parameters.
All tests pass.
> Add demonstration tests (BubbleTest / SharingTest)

- Code/src/main/java/nl/utwente/group10/haskell/hindley/HindleyMilner.java
- Code/src/main/java/nl/utwente/group10/haskell/type/VarT.java
- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/components/anchors/InputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/lines/Connection.java
- Code/src/test/java/nl/utwente/group10/haskell/type/UnificationTest.java
Fixed invalidateConnectionStateCascading() getting called whenever you moved a Block.
Heb het gehele error triggering verbeterd, nu gebaseerd op het invalidaten van de connection state.
Vervolgens worden de error methoden wat netter aangeroepen.
Ik geloof dat we uiteindelijk uitkwamen op geen error weergave in het block, dat gebeurt momenteel wel, maar nu is dit geheel aan de styleclass (geen error styleclass = geen error weergave).
> UI-errors display now gets correctly updated. Small misc fixes.

- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/Main.java
- Code/src/main/java/nl/utwente/group10/ui/ZoomOverlay.java
- Code/src/main/resources/ui/style.css
Also disables scroll-to-zoom on touch, as the one-finger scroll gesture
conflicted with the one-finger pan gesture.
It should be easy to add other buttons as well, if required.
> Add zoom button toolbar/overlay

- Code/src/main/java/nl/utwente/group10/ui/Main.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/RGBBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/SliderBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java
- Code/src/main/java/nl/utwente/group10/ui/menu/MainMenu.java
- Code/src/main/resources/ui/RGBBlock.fxml
- Code/src/main/resources/ui/SliderBlock.fxml
The slider block allows inputting floating point values from 0.0 to 1.0 in a
convenient fashion (if you want another range, just add a multiplication or
addition block).
The RGB block displays a triple of floating point values as a colored pane. Of
course, `(0, 0, 0)` is black, while `(1.0, 1.0, 1.0)` is white.
> Add slider and RGB blocks

- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/GraphBlock.java
- Code/src/main/java/nl/utwente/group10/ui/menu/MainMenu.java
- Code/src/main/resources/ui/GraphBlock.fxml
- Code/src/main/resources/ui/style.css
GraphBlocks take a single input: a function from Float to Float (could perhaps
be Floating to Num, I haven't checked). It then draws the results of that function
as a nice-looking line graph by mapping it over a (Haskell-generated) list of
intermediate values.
The horizontal range is fixed for now (from -5 to +5), as is the step size; the
vertical axis will automatically scale with the input data.
This PR also contains a (temporary, I hope) means of changing the bowtie index
on functions with the arrow keys, as without that, it's hard to partially apply
functions.
Like PR #94, this PR depends on `invalidateConnectionState` to do something
that doesn't have anything to do with connection state - I'm not sure how to
fix that.
> Add first version of graph block

- Code/src/main/java/nl/utwente/group10/ui/components/anchors/OutputAnchor.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/GraphBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/InputBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/OutputBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java
Not all implementations of all methods of the InputBlock/OutputBlock are very interesting. This commit introduces some reasonable default implementations of InputBlock/OutputBlock methods and removes some superfluous ones.
> Simplify InputBlock/OutputBlock interfaces

- Code/src/main/java/nl/utwente/group10/haskell/expr/Apply.java
- Code/src/main/java/nl/utwente/group10/haskell/expr/Expr.java
- Code/src/main/java/nl/utwente/group10/haskell/expr/Function.java
- Code/src/main/java/nl/utwente/group10/haskell/expr/Ident.java
- Code/src/main/java/nl/utwente/group10/haskell/expr/Value.java
- Code/src/main/java/nl/utwente/group10/ui/InspectorWindow.java
- Code/src/test/java/nl/utwente/group10/haskell/expr/ExprTest.java
Part of #112.
Also fixes InspectorWindow to not (possibly) modify types when UI calls type checker correctly.
> Let Expr cache expressions

- Code/src/main/java/nl/utwente/group10/haskell/hindley/HindleyMilner.java
- Code/src/main/java/nl/utwente/group10/haskell/type/VarT.java
- Code/src/test/java/nl/utwente/group10/haskell/type/ApplyTest.java
- Code/src/test/java/nl/utwente/group10/haskell/type/UnificationTest.java
I distinctly remember claiming that, when one unifies two variable types
that both have typeclasses, one should take the intersection of their
respective constraints.
This is, of course, patent nonsense. If you have two functions:
f :: (Show a, Fruit a) => a -> a
f x = x
g :: (Show b, Vehicle b) => b -> b
g y = y
And you define a third function:
h z = (f z, g z)
Then z must be Show, Fruit *and* Vehicle (a banana mobile, perhaps?)
GHCi will gladly give you the actual signature:
h :: (Show t, Vehicle t, Fruit t) => t -> (t, t)
In other words, the sets of constraints are unioned, not intersected,
with one another. This commit is a first attempt at that.
> HM: Union typeclasses instead of intersecting them

- Code/src/main/resources/catalog/catalog.xml
String is a type alias for `[Char]`, but our type checker doesn't know that.
This replaces all mentions of String with `[Char]`.
> Replace mentions of 'String' in catalog with '[Char]'.

- Code/src/test/java/nl/utwente/group10/haskell/expr/FunctionTest.java
Function now adds these parentheses to ensure precedence is correct.
> Add a pair of parentheses to FunctionTest

- Code/pom.xml
- Code/src/main/java/nl/utwente/group10/ui/ButtonOverlay.java
- Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/group10/ui/InspectorWindow.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/function/FunctionBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/blocks/output/ValueBlock.java
- Code/src/main/java/nl/utwente/group10/ui/components/lines/Connection.java
- Code/src/main/java/nl/utwente/group10/ui/components/menu/GlobalMenu.java
- Code/src/main/java/nl/utwente/group10/ui/serialize/Bundleable.java
- Code/src/main/java/nl/utwente/group10/ui/serialize/Exporter.java
- Code/src/main/java/nl/utwente/group10/ui/serialize/Importer.java
- Code/src/main/resources/ui/InspectorWindow.fxml
This PR implements the 'Save' and 'Save as' actions. 
The (JavaFX) components are not Java `Serializable`. Instead of using Java's built-in serialization, this PR serializes the program graph to a nicely formatted JSON tree. Components can mark themselves as serializable by implementing the `Bundleable` interface.
The JSON serialization is shown in the Inspector to help with debugging.
> Add save/save as actions and JSON serializer

- Code/src/main/java/nl/utwente/viskell/haskell/expr/Annotated.java
- Code/src/main/java/nl/utwente/viskell/haskell/expr/Lambda.java
This makes both expressions introspectable in the inspector window.
> Add getChildren methods to Lambda and Annotated

- Code/src/main/java/nl/utwente/viskell/ui/components/ArgumentSpace.java
Fix case where functions without arguments (i.e. `pi`) would throw an
array index out of bounds exception.
> Fix ArrayIndexOutOfBounds in ArgumentSpace

- Code/src/main/java/nl/utwente/viskell/ghcj/GhciSession.java
- Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java
- Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/GraphBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/RGBBlock.java
- Code/src/test/java/nl/utwente/viskell/ghcj/GhciSessionTest.java
This enables GhciSession to execute Haskell snippets on a different
thread than the main thread.
GhciSession is an AbstractExecutionThreadService from Guava. It takes Haskell
source to execute off the work queue, which is read from a (singular)
execution thread, and filled by anything that wants something executed.
Push and pull methods on GhciSession return 'immediately', and never
throw HaskellException. If (when) something goes wrong, the future will
be set to unsuccesful, which means `get` will throw ExecutionException
or the unsuccesful callback will be called.
DisplayBlock uses callbacks to delay updating of its label until the
future is completed (i.e. evaluation should not block the UI).
RGBBlock and GraphBlock wait for their results for now (i.e. their
behaviour should be …
> Make GhciSession a Service that returns Futures

- Code/src/main/java/nl/utwente/viskell/ghcj/GhciSession.java
- Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/Main.java
- Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/GraphBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/RGBBlock.java
We can always build a GhciSession work queue, even if it doesn't
necessarily answer any requests (say, because ghci is not installed).
Also reworks the 'check if we can use ghci' logic in Main.
> Make CustomUIPane's GhciSession not optional

- Code/src/main/java/nl/utwente/viskell/ui/CircleMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
- Code/src/main/java/nl/utwente/viskell/ui/components/Block.java
- Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/FunctionBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/GraphBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java
- Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java
- Code/src/main/java/nl/utwente/viskell/ui/components/ValueBlock.java
- Code/src/main/resources/ui/DefinitionBlock.fxml
- Code/src/main/resources/ui/LambdaContainer.fxml
Also types now only propagate outwards from a lambda.
Depends on #260.
> Split Defintion block into a inner and outer part 

- Code/src/main/java/nl/utwente/viskell/ghcj/GhciSession.java
- Code/src/main/java/nl/utwente/viskell/ui/InspectorWindow.java
- Code/src/main/resources/ui/InspectorWindow.fxml
This has the GhciSession log the last LOG_SIZE (16) error descriptions
from Ghci. They are only shown in the InspectorWindow for now.
> Log the last sixteen Haskell runtime errors

- Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/components/SimulateBlock.java
- Code/src/main/resources/catalog/clash.xml
- Code/src/main/resources/ui/SimulateBlock.fxml
- Code/src/main/resources/ui/colours.css
- Code/src/main/resources/ui/layout.css
> SimulateBlock is CLaSH-specific block that is a counterpart to the `simulate`
> function in Clash. Expects a function that turns a Signal of monotonically
> increasing numbers into a Signal of representable result values.
> 
> While signals are infinite, SimulateBlock only shows the first N
> iterations/steps.
It's basically a poor man's (stepping) debugger.
> Add first version of SimulateBlock

- Code/src/main/java/nl/utwente/viskell/ghcj/ClashEvaluator.java
- Code/src/main/java/nl/utwente/viskell/ghcj/GhciEvaluator.java
- Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java
- Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java
One is avoiding a concurrent modifications exceptions on deleting a lambda or case.
Second is stopping a warning from breaking evaluator value parsing.
> Fix two small bugs

- Code/src/main/java/nl/utwente/viskell/ui/components/BinOpApplyBlock.java
- Code/src/main/java/nl/utwente/viskell/ui/components/Block.java
- Code/src/main/java/nl/utwente/viskell/ui/components/FunApplyBlock.java
- Code/src/main/resources/ui/ArgumentSpace.fxml
- Code/src/main/resources/ui/BinOpApplyBlock.fxml
- Code/src/main/resources/ui/ChoiceBlock.fxml
- Code/src/main/resources/ui/DefinitionBlock.fxml
- Code/src/main/resources/ui/DisplayBlock.fxml
- Code/src/main/resources/ui/FunApplyBlock.fxml
- Code/src/main/resources/ui/FunctionBlock.fxml
- Code/src/main/resources/ui/GraphBlock.fxml
- Code/src/main/resources/ui/MatchBlock.fxml
- Code/src/main/resources/ui/SimulateBlock.fxml
- Code/src/main/resources/ui/SliderBlock.fxml
By default panes use their outside bounds to determine whether they are the target of a click, but for blocks with all these anchors sticking out those bounds are too large.
> Use the actual area of blocks for the clickable region

- Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java
It was too easy to accidentally connect a block with itself, with obvious bad effects.
> Do not allow wires connect an input with an output of the same block

- Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java
- Code/src/main/resources/ui/DisplayBlock.fxml
Also dropped show constraint, which only causes typelabels to be bigger everywhere.
> Show type on unshowable inputs of a displayblock

- Code/src/main/java/nl/utwente/viskell/ui/BlockContainer.java
- Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java
- Code/src/main/java/nl/utwente/viskell/ui/components/FunctionReference.java
- Code/src/main/java/nl/utwente/viskell/ui/components/WrappedContainer.java
Methods in an interface are always public, so the `public` keyword is
unnecessary.
> Remove superfluous keywords from some interfaces

- Code/src/main/java/nl/utwente/viskell/ui/GlobalContextMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/MacTopMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/Main.java
- Code/src/main/java/nl/utwente/viskell/ui/MainOverlay.java
- Code/src/main/java/nl/utwente/viskell/ui/MenuActions.java
- Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java
Added MacTopMenu to create a Top application menu for Mac.
GlobalMenu refactored into GlobalContextMenu that is used for on-screen context menu, and MenuActions which are shared between all menus.
MainOverlay now wraps overlay in a BorderPane that accepts a TopMenu, and when detected we are running on a Mac it replaces the on-screen
context menu with a TopMenu that does the same actions (except full-screen which is a window control in Mac OS X).
Avoid referencing overlay via Main.java public overflow, use the parameter passed in to the constructor and pass down to refreshTheme()
MainOverlay doesn't need to be public in Main.java any more.
> Use a TopMenu on Mac OS X instead of onscreen context menu for touch devices.

- Code/src/main/java/nl/utwente/viskell/ui/MacTopMenu.java
- Code/src/main/java/nl/utwente/viskell/ui/MainOverlay.java
- Code/src/main/java/nl/utwente/viskell/ui/MenuActions.java
- Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java
- Code/src/test/java/nl/utwente/viskell/ui/MenuActionsTest.java
- Code/src/test/java/nl/utwente/viskell/ui/ToplevelPaneITCase.java
Added Keyboard shortcuts for most menu items.
NOTE: There is a strange bug on Mac that Command & '-' to zoom out doesn't work on JavaFX.
Moved the zoom() method into ToplevelPane() which is the Pane it actually changes the view of and hence belongs to.
Moved the showPreferences() and showInspector() methods into MenuActions as they can be totally self-contained in there.
Added unit tests for some of the menu actions
> Add keyboard shortcuts to most menu items

- Code/pom.xml
This pom addition avoids a warning in the output of “man verify” as the reporting plugins need a separate property for the encoding.
> Avoid encoding warning in verify output
