viskell/viskell

Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/components/Connection.java, Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java, Code/src/main/resources/ui/FunctionBlock.fxml, Code/src/main/resources/ui/style.css, Code/src/test/java/nl/utwente/group10/ui/components/FunctionBlockTest.java
Changes the constructor of FunctionBlock to accept a type from, say, the catalog instead of a number of parameters.
This PR also introduces a slight change to how blocks look, as I still don't quite understand the UI sketches. We'll have to evaluate the looks of blocks when @Kristel-92's sketches come in.
=> Construct function blocks from catalog

Code/src/main/antlr4/nl/utwente/group10/haskell/typeparser/Type.g4, Code/src/main/java/nl/utwente/group10/haskell/hindley/HindleyMilner.java, Code/src/main/java/nl/utwente/group10/haskell/typeparser/TypeBuilderListener.java, Code/src/main/java/nl/utwente/group10/tcc/TypeCheckerChecker.java, Code/src/main/resources/tcc/TypeCheckerChecker.fxml, Code/src/test/java/nl/utwente/group10/haskell/typeparser/TypeBuilderTest.java
The TypeCheckerChecker is a simple GUI interface to the 'type inference' (major
air quotes there) part of the backend, which allows fiddling around with it for
a bit to see if it makes any obvious mistakes.
=> Add TypeCheckerChecker

Code/src/main/java/nl/utwente/group10/ghcj/GhciEvaluator.java, Code/src/main/java/nl/utwente/group10/ghcj/GhciSession.java, Code/src/main/java/nl/utwente/group10/haskell/package-info.java, Code/src/main/java/nl/utwente/group10/tcc/TypeCheckerChecker.java, Code/src/main/java/nl/utwente/group10/tcc/package-info.java, Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/components/Block.java, Code/src/main/java/nl/utwente/group10/ui/components/Connection.java, Code/src/main/java/nl/utwente/group10/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/DisplayBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/Line.java, Code/src/main/java/nl/utwente/group10/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/ValueBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/package-info.java, Code/src/main/java/nl/utwente/group10/ui/package-info.java
Documentation, code smells, etc.
Also removed some obviously unused things.
=> Cleanup a lot of packages

Code/src/main/java/nl/utwente/group10/ghcj/GhciEvaluator.java, Code/src/main/java/nl/utwente/group10/ghcj/GhciSession.java, Code/src/main/java/nl/utwente/group10/haskell/package-info.java, Code/src/main/java/nl/utwente/group10/tcc/TypeCheckerChecker.java, Code/src/main/java/nl/utwente/group10/tcc/package-info.java, Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/components/Block.java, Code/src/main/java/nl/utwente/group10/ui/components/Connection.java, Code/src/main/java/nl/utwente/group10/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/DisplayBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/Line.java, Code/src/main/java/nl/utwente/group10/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/ValueBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/package-info.java, Code/src/main/java/nl/utwente/group10/ui/package-info.java, Code/src/test/java/nl/utwente/group10/ui/components/FunctionBlockTest.java
Converted tabs in ui package to spaces
=> Cleanup whitespace

Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/MainMenu.java
It also removes the 'Add a function' item, promoting categories to their very own submenus.
=> Refactor main (context) menu into its own class

.latex.yml
This has ShareLaTeX compile every change, making it easier to see the rendered state of the report:
https://www.sharelatex.com/github/repos/wandernauta/Groep10/builds/latest/output.pdf
=> Add ShareLaTeX .latex.yml file

Code/src/main/java/nl/utwente/group10/ui/MainMenu.java
This is a proof of concept to modify the MainMenu to include Value and Display Blocks. Currently I am unsatisfied with the code. Please review and advise on possible refactoring and changes.
=> MainMenu modification for Value and Display Blocks

Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/MainMenu.java, Code/src/main/java/nl/utwente/group10/ui/components/Connection.java, Code/src/main/java/nl/utwente/group10/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/ConnectionLine.java, Code/src/main/java/nl/utwente/group10/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/package-info.java, Code/src/main/java/nl/utwente/group10/ui/components/package-info.java, Code/src/main/resources/ui/DisplayBlock.fxml, Code/src/main/resources/ui/FunctionBlock.fxml, Code/src/main/resources/ui/ValueBlock.fxml, Code/src/test/java/nl/utwente/group10/ui/components/blocks/ComponentTest.java, Code/src/test/java/nl/utwente/group10/ui/components/blocks/DisplayBlockTest.java, Code/src/test/java/nl/utwente/group10/ui/components/blocks/FunctionBlockTest.java, Code/src/test/java/nl/utwente/group10/ui/components/blocks/ValueBlockTest.java
Created a new separate package for Block components since their number was growing to be quite large. Fixed whitespace for all of the UI classes that were using tabs.
=> UI package refactoring and whitespace fixing

Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java
=> Javadoc and whitespace cleanup for Block.java

Code/src/main/java/nl/utwente/group10/haskell/catalog/HaskellCatalog.java, Code/src/main/java/nl/utwente/group10/haskell/env/Env.java, Code/src/main/java/nl/utwente/group10/haskell/expr/Ident.java, Code/src/main/java/nl/utwente/group10/haskell/type/ConstT.java, Code/src/main/java/nl/utwente/group10/haskell/type/Type.java, Code/src/main/java/nl/utwente/group10/haskell/type/VarT.java, Code/src/main/resources/catalog/catalog.xml, Code/src/test/java/nl/utwente/group10/haskell/expr/ApplyTest.java, Code/src/test/java/nl/utwente/group10/haskell/expr/ExprTest.java, Code/src/test/java/nl/utwente/group10/haskell/expr/IdentTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/ConstTTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/VarTTest.java
- Types have now correct ```equals``` and ```compareTo``` methods
- Ident expressions now use fresh types
Would like input on implementation (improvements, how to clean up code)
=> Improvements to type system

Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/components/CustomAlert.java, Code/src/main/resources/ui/Alert.fxml, Code/src/main/resources/ui/style.css
So far, at least four of us have tried running the program on a machine that didn't have GHC installed. This will not work. This PR adds a nice graphical message to the interface itself if there's a problem with ghci.
=> Show an alert if a noop evaluation with GHCi fails

Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/resources/ui/style.css
This adds keyboard bindings for panning and zooming. It also moves
delete key handling from Main to CustomUIPane.
=> Add panning and zooming with keyboard

Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/components/ComponentLoader.java, Code/src/main/java/nl/utwente/group10/ui/components/CustomAlert.java, Code/src/main/java/nl/utwente/group10/ui/components/anchors/ConnectionAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/anchors/InputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/anchors/OutputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/Block.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/DisplayBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/lines/Connection.java, Code/src/main/java/nl/utwente/group10/ui/components/lines/ConnectionLine.java, Code/src/main/java/nl/utwente/group10/ui/menu/MainMenu.java
Converted whitespace usage to Google styled Java, rewtrote documentation and added where neccessary.
=> Refactoring of UI classes

Code/src/test/java/nl/utwente/group10/haskell/type/ApplyTest.java
The ApplyTest previously in PR 51, also updated (had some bugs).
Due to recent backend fixes the test now succeeds.
=> Added (and updated) ApplyTest

Code/src/main/java/nl/utwente/group10/ui/components/blocks/FunctionBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/lines/Connection.java, Code/src/main/resources/ui/FunctionBlock.fxml, Code/src/main/resources/ui/style.css
Stelt niet veel voor, maar geeft iets duidelijker weer wat het uiteindelijk moet worden.
Dit moet waarschijnlijk wel weer net iets anders als we de bowtie visueel gaan weergeven, maar tot dan werkt dit.
=> Moved type display into function block

Code/src/main/java/nl/utwente/group10/haskell/type/VarT.java, Code/src/test/java/nl/utwente/group10/haskell/type/ApplyTest.java
=> Extra ApplyTest test case to show a bug.(currently fails)

Code/src/main/java/nl/utwente/group10/haskell/expr/Apply.java, Code/src/main/java/nl/utwente/group10/haskell/expr/Expr.java, Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/InspectorWindow.java, Code/src/main/resources/ui/InspectorWindow.fxml
This PR adds an 'inspector' window that shows the expression tree as well as
the generated Haskell source for the selected block.
Since #82, CustomUIPane is no longer notified when the program changes, so you
may have to click the 'refresh' button on the Inspector if you change your
program and it doesn't seem to update.
The window is shown when the Z key is pressed.
=> Add inspector window

Code/src/main/java/nl/utwente/group10/haskell/expr/Function.java, Code/src/main/java/nl/utwente/group10/haskell/type/ConstT.java, Code/src/main/java/nl/utwente/group10/haskell/type/FuncT.java, Code/src/main/java/nl/utwente/group10/haskell/type/ListT.java, Code/src/main/java/nl/utwente/group10/haskell/type/TupleT.java, Code/src/main/java/nl/utwente/group10/haskell/type/Type.java, Code/src/main/java/nl/utwente/group10/haskell/type/VarT.java, Code/src/test/java/nl/utwente/group10/haskell/expr/FunctionTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/ConstTTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/TypeTest.java
=> Basic backend implementation of user defined functions

Code/src/main/java/nl/utwente/group10/ui/menu/CircleMenu.java
This makes the animation for the context menu near instantaneous.
Pending my review of what has been changed for context menus in PR #120 I will add more of the requested fixes.
=> ctx Menu fixes

.travis.yml
This has Travis install Java minor revision 45, which has input dialogs in JavaFX.
=> Have Travis install newest Java

Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/menu/CircleMenu.java, Code/src/main/java/nl/utwente/group10/ui/menu/FunctionMenu.java
Cleaned several menu related issues and code.
=> Menu cleaning

Code/src/main/java/nl/utwente/group10/ui/Main.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/SliderBlock.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/ValueBlock.java, Code/src/main/java/nl/utwente/group10/ui/menu/FunctionMenu.java, Code/src/test/java/nl/utwente/group10/ui/components/blocks/ValueBlockTest.java
Adding a ValueBlock now prompts for a value, which can be any valid Haskell
expression.
=> Add custom ValueBlock values

Code/src/main/java/nl/utwente/group10/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/group10/ui/InspectorWindow.java, Code/src/main/java/nl/utwente/group10/ui/ZoomOverlay.java, Code/src/main/java/nl/utwente/group10/ui/handlers/AnchorHandler.java, Code/src/main/java/nl/utwente/group10/ui/handlers/ConnectionCreationManager.java
Pay special attention to ConnectionCreationManager -> finishConnection
=> Ui doc update

Report/Chapters/Manual.tex
This user guide would help users to get started with the program.
=> Add a one-page User Guide

Report/Chapters/Testplan.tex
=> added Acceptance tests

Code/src/main/resources/ui/DefinitionBlock.fxml
=> Fixed funcdef argument spacing.

Report/Chapters/Design.tex, Report/Chapters/Implementation.tex, Report/Chapters/Process.tex, Report/Chapters/Requirements.tex
This is currently a work in progress, but feedback is already welcome.
This will probably change stuff in the entire report, since I am just reading it from top to bottom.
=> Report remarks

Code/src/main/java/nl/utwente/group10/haskell/type/FunType.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeChecker.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeVar.java, Code/src/test/java/nl/utwente/group10/haskell/type/ConstTTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/SharingTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/UnificationTest.java
Add missing symmetric case in de typechecker unification.
Enforce correct instancing behaviour in TypeVar.
And some debugging improvements
=> Fix TypeVar instance bug

Code/src/main/antlr4/nl/utwente/group10/haskell/typeparser/Type.g4, Code/src/main/java/nl/utwente/group10/haskell/type/TupleTypeCon.java, Code/src/main/java/nl/utwente/group10/haskell/type/Type.java, Code/src/main/java/nl/utwente/group10/haskell/typeparser/TypeBuilderListener.java, Code/src/main/resources/catalog/catalog.xml, Code/src/test/java/nl/utwente/group10/haskell/type/TypeTest.java, Code/src/test/java/nl/utwente/group10/haskell/typeparser/TypeBuilderTest.java
This parses every combination of a type variable followed by something else
as a type application.
Also adds the Functor type class and the fmap function to the catalog.
=> Add type application in the type parser (#177)

Code/src/main/java/nl/utwente/group10/ui/components/menu/FunctionMenu.java, Code/src/main/resources/catalog/catalog.xml, Code/src/main/resources/ui/FunctionMenu.fxml, Code/src/test/java/nl/utwente/group10/haskell/catalog/HaskellCatalogTest.java
Less categories and close button on top.
=> Minor tweaks to the function menu to make it less annoying

Code/src/main/java/nl/utwente/group10/haskell/expr/Binder.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeChecker.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeScope.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeVar.java, Code/src/main/java/nl/utwente/group10/ui/components/anchors/InputAnchor.java, Code/src/main/java/nl/utwente/group10/ui/components/blocks/function/FunctionBlock.java, Code/src/test/java/nl/utwente/group10/haskell/expr/Annotated.java, Code/src/test/java/nl/utwente/group10/haskell/type/ClassesTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/LambdaTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/SharingTest.java
How very small changes can make a big difference...
Accidently depends on PR #191.
=> Fixing the updating of input argument types

Code/src/main/java/nl/utwente/group10/haskell/expr/Binder.java, Code/src/main/java/nl/utwente/group10/haskell/expr/Expression.java, Code/src/main/java/nl/utwente/group10/haskell/type/ConstraintSet.java, Code/src/main/java/nl/utwente/group10/haskell/type/ListTypeCon.java, Code/src/main/java/nl/utwente/group10/haskell/type/TupleTypeCon.java, Code/src/main/java/nl/utwente/group10/haskell/type/Type.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeApp.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeChecker.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeClass.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeCon.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeScope.java, Code/src/main/java/nl/utwente/group10/haskell/type/TypeVar.java, Code/src/main/java/nl/utwente/group10/haskell/typeparser/TypeBuilder.java, Code/src/test/java/nl/utwente/group10/haskell/expr/Annotated.java, Code/src/test/java/nl/utwente/group10/haskell/type/ClassesTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/LambdaTest.java, Code/src/test/java/nl/utwente/group10/haskell/type/SharingTest.java
Show, Ord, and alike on lists, tuples, Maybe and more.
depends on PR #191
=> Add support for simple type classes on nested types

Code/src/main/java/nl/utwente/viskell/ui/ConnectionCreationManager.java, Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/RGBBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/SliderBlock.java
=> Fix connection creation to avoid leaving partial ones in the ui in some corner cases

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
Solves updating of connected blocks on block removal as observed in #208.
=> Use proper removal methods in removeBlock

Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java, Code/src/main/resources/ui/DisplayBlock.fxml, Code/src/main/resources/ui/SliderBlock.fxml, Code/src/main/resources/ui/style.css
It doesn't look quite nice yet, but had enough of javafx for today.
=> Show value in slider and type in display block

Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionLine.java
Uses cubic root scaling factor instead of approximation, and short lines are more flexible now.
=> Rewrite of bezier curve point calculation

Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java
This should fix both #219 and #170.
=> Fix cornercases in the new updating strategy

Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/RGBBlock.java, Code/src/main/resources/ui/DisplayBlock.fxml, Code/src/main/resources/ui/RGBBlock.fxml
Replaces bindings on layoutX with the JavaFX TilePane layout.
=> Clean up positioning of RGBBlock input anchors

Code/src/main/java/nl/utwente/viskell/ui/ButtonOverlay.java, Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/resources/ui/DefinitionBlock.fxml, Code/src/main/resources/ui/FunctionMenu.fxml, Code/src/main/resources/ui/style.css
See the diff for trivial changes for convenience.
=> Tweak sizes of things for practicality or uniformity

Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java
Should solve the example from #183 and related things.
=> Fix change propagation through error connections

Code/src/main/java/nl/utwente/viskell/ghcj/GhciEvaluator.java, Code/src/main/resources/catalog/catalog.xml
Cleans up the XML a bit, and adds some functions and constructors for working
with tuples, booleans, Maybe and Either.
Replaces #238, fixes #237.
=> Improvements and additions for catalog.xml

Code/src/main/java/nl/utwente/viskell/ghcj/GhciEvaluator.java
and removed manually loading Prelude.
=> Added -ignore-dot-ghci parameter to GHCi

Code/src/main/java/nl/utwente/viskell/ui/ConnectionCreationManager.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java, Code/src/main/java/nl/utwente/viskell/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/InputArgument.java, Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/RGBBlock.java, Code/src/main/resources/ui/DrawWire.fxml, Code/src/main/resources/ui/style.css
=> Refactored anchors and made it possible for all input anchors to show errors

Code/src/main/java/nl/utwente/viskell/ui/CircleMenu.java, Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/GraphBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/ValueBlock.java
Also simplifies visual state updates a bit
=> Make Block more abstract and related cleanups

Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java, Code/src/main/resources/ui/PreferencesWindow.fxml, Code/src/main/resources/ui/debugColours.css
Currently simply a fixed set of paths to the CSS files. A theme class or
map can be made later on. Likewise a set of all the existing stages so
you don't have to hard-code replacing the style of each stage.
(That's what the commit says already.)
=> Added preferences option for the UI style

Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java, Code/src/main/resources/ui/PreferencesWindow.fxml
=> Add style reload button to the preferences

Code/src/main/java/nl/utwente/ewi/caes/tactilefx/control/TactilePane.java, Code/src/main/java/nl/utwente/ewi/caes/tactilefx/debug/DebugParent.java, Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java, Code/src/main/resources/ui/PreferencesWindow.fxml, Code/src/main/resources/ui/debugColours.css
and preventing the function menu from being dragged along
=> Fixed dragging nodes

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/GlobalMenu.java, Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java, Code/src/main/java/nl/utwente/viskell/ui/serialize/Exporter.java, Code/src/main/resources/ui/debugColours.css
=> Make the custom uipane layered

Code/src/main/java/nl/utwente/viskell/ui/InspectorWindow.java, Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/resources/ui/colours.css, Code/src/main/resources/ui/debugColours.css, Code/src/main/resources/ui/layout.css
Just a quickie.
Having the inspector window pop up in the middle of the screen is annoying.
=> Debug improvements

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/InspectorWindow.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/resources/ui/colours.css
This merges the stale no_global_select branch (replacing PR #268) and removes keyboard events from CustomUIPane.
=> Remove keyboard events and selected block property

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
These do not (should not) change CustomUIPane's behaviour.
=> Minor cleanups for CustomUIPane

Code/src/main/java/nl/utwente/viskell/ui/CircleMenu.java, Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/DragContext.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java
This should make a fast 'rightclick' possible for touch, but that needs testing on the big screen.
=> Add secondary action to dragcontext and use it for circlemenu

Code/src/main/java/nl/utwente/viskell/haskell/env/DefinitionFunction.java, Code/src/main/java/nl/utwente/viskell/haskell/env/FunctionInfo.java, Code/src/main/java/nl/utwente/viskell/haskell/expr/FunVar.java, Code/src/main/java/nl/utwente/viskell/haskell/expr/Lambda.java, Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/java/nl/utwente/viskell/ui/components/BinderAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/BlockContainer.java, Code/src/main/java/nl/utwente/viskell/ui/components/ChoiceBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/DisplayBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunApplyBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/GraphBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java, Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java, Code/src/main/java/nl/utwente/viskell/ui/components/MatchBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/ResultAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/SimulateBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/ValueBlock.java, Code/src/test/java/nl/utwente/viskell/haskell/expr/LambdaTest.java
modified expression generation to accommodate for them.
See DefinitionFunction, DefinitionBlock and FunctionBlock for the creation of an application.
The rest is a change from passing required Blocks to required OutputAnchors while generating an expression.
=> Added application block for DefinitionBlocks and

Code/src/main/java/nl/utwente/viskell/haskell/type/ConstraintSet.java, Code/src/main/java/nl/utwente/viskell/haskell/type/Type.java, Code/src/main/java/nl/utwente/viskell/haskell/type/TypeScope.java, Code/src/main/java/nl/utwente/viskell/haskell/type/TypeVar.java, Code/src/main/java/nl/utwente/viskell/ui/components/Connection.java, Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java
=> Add the concept of rigid typevars for enforcing polymorpic signatures

Code/src/main/java/nl/utwente/viskell/ui/components/SliderBlock.java
=> Avoid moving block on dragging slider

Code/src/main/java/nl/utwente/viskell/haskell/type/TypeVar.java
=> Fix constraint check for rigid type variables

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java, Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java
Also prevent accidental movement of containers while drawing wires.
=> Allow opening of the function menu inside container areas

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java, Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java
NPE on an optional, longpress functionmenu, and draw wire updating.
=> Various small bug fixes

Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/components/SliderBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/ValueBlock.java, Code/src/main/resources/ui/SliderBlock.fxml
Also the new sliders allow negative numbers, and the scaling is relative and exponential.
=> Make slider blocks more usefull and add an integer variant

Code/src/main/java/nl/utwente/viskell/ui/CustomUIPane.java
=> More reliable function menu spawning with touch

Code/src/main/java/nl/utwente/viskell/ui/CircleMenu.java, Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java
Also it is not a javafx Popup anymore, because that is totally broken with multitouch.
=> Rewritten circle menu to work well with multitouch

Code/src/main/resources/catalog/haskell.xml, Code/src/test/java/nl/utwente/viskell/haskell/env/HaskellCatalogTest.java
Added lots of Data.List functions, applicatives, monads, and other abstractions.
And some reorganization to keep to catagories sane, also removed some rare and obscure things.
=> Large catalog update and refactoring

Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java, Code/src/main/resources/ui/InputAnchor.fxml, Code/src/main/resources/ui/OutputAnchor.fxml
Also tweaked various cornercases in mouse event handling.
=> Resumable wire drawing when released for a short time on nothing

Code/src/main/java/nl/utwente/viskell/ui/WireMenu.java, Code/src/main/java/nl/utwente/viskell/ui/components/JoinerBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java, Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/SplitterBlock.java
=> Add specialized wire splitter and wire joiner blocks

Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java, Code/src/main/java/nl/utwente/viskell/ui/components/Block.java, Code/src/main/java/nl/utwente/viskell/ui/components/ChoiceBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/DrawWire.java, Code/src/main/java/nl/utwente/viskell/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/LambdaContainer.java, Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java, Code/src/main/java/nl/utwente/viskell/ui/components/OutputAnchor.java
Also indicates whether connecting that anchor will cause a type error.
=> Make anchors visually react to a wire getting nearby

Code/src/main/java/nl/utwente/viskell/haskell/env/FunctionInfo.java, Code/src/main/java/nl/utwente/viskell/ui/CircleMenu.java, Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/components/ApplyAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/ConnectionAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/DefinitionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunApplyBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunctionBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/FunctionReference.java, Code/src/main/java/nl/utwente/viskell/ui/components/InputAnchor.java, Code/src/main/java/nl/utwente/viskell/ui/components/LibraryFunUse.java, Code/src/main/java/nl/utwente/viskell/ui/components/NestedFunction.java, Code/src/main/resources/ui/FunApplyBlock.fxml, Code/src/main/resources/ui/FunctionBlock.fxml, Code/src/test/java/nl/utwente/viskell/ui/components/FunctionBlockTest.java
The apply block can still be improved a lot, but I just want to get the basics and the refactorings in.
=> Add initital version of an apply block and related refactorings

Code/src/main/java/nl/utwente/viskell/ui/components/Block.java
=> Stabilize function block knot by not centering the block

Code/src/main/java/nl/utwente/viskell/ui/components/ChoiceBlock.java, Code/src/main/java/nl/utwente/viskell/ui/components/Lane.java, Code/src/main/resources/ui/ChoiceBlock.fxml, Code/src/main/resources/ui/Lane.fxml, Code/src/main/resources/ui/colours.css, Code/src/main/resources/ui/layout.css
including a type label for the output anchor of a choice block
=> Restyle ChoiceBlock to match LambdaBlock

Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java, Code/src/main/java/nl/utwente/viskell/ui/TouchContext.java
A connection can be cut by drawing a line across it and then tracing that line back to its starting point.
This can be done either with as a single finger drag or dragging with the primary mouse button.
Also the panning by mouse has been moved to a secondary button.
=> Gesture for quickly cutting a connection wire

Code/src/main/java/nl/utwente/viskell/ui/FunctionMenu.java, Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java, Code/src/main/java/nl/utwente/viskell/ui/TouchContext.java, Code/src/main/resources/ui/PreferencesWindow.fxml
This could use some testing on non windows devices.
Replaces PR #440.
Unfortunately I could not get zooming to work on touchpad too, and I don't know whether to blame the OS or JavaFX for that.
=> Support panning using a touchpad or scrollwheel

Code/src/main/java/nl/utwente/viskell/ui/Main.java, Code/src/main/java/nl/utwente/viskell/ui/MainOverlay.java, Code/src/main/java/nl/utwente/viskell/ui/MenuActions.java, Code/src/main/java/nl/utwente/viskell/ui/PreferencesWindow.java, Code/src/test/java/nl/utwente/viskell/ui/MenuActionsTest.java
Restore the display of on-screen zoom controls. Some minor code changes, warnings removals and comments added in the process.
=> Restore the on-screen zoom controls
